### ISSUE TITLE
iso verification

### ISSUE THREAD

**Issue by Sigrunnr** [dessington/dxt2#1]
Hi, just about to try your project out but noticed you have no verification signatures or sha's available, do you plan to atleast have a sha1sum to verify the iso ?

this is the sha1sum i get, can you verify this please.

08aff47db981aa6a9f5c6b8b70730b5306183748  dxt2rc1.iso

**Comment by dessington** [comment]
Hi, 

Thanks for your interest. I have created one now:
027597343e7547c95af5d28330fa440d75cb7779. I've posted it on github.

---

Regards,
Jason Dessington
CUSTOMWEB 

On 2020-04-28 11:33, Sigrunnr wrote:

> Hi, just about to try your project out but noticed you have no verification signatures or sha's available, do you plan to atleast have a sha1 to verify the iso ? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/dessington/dxt2/issues/1
[2]

**Comment by dessington** [comment]
Hope that helps.

---

Regards,
Jason Dessington
CUSTOMWEB 

On 2020-04-28 11:33, Sigrunnr wrote:

> Hi, just about to try your project out but noticed you have no verification signatures or sha's available, do you plan to atleast have a sha1 to verify the iso ? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/dessington/dxt2/issues/1
[2]
