### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by Sigrunnr** [dessington/dxt2#2]
Hi again, gave your iso a try on a bare metal machine with no operating system so just a test box. The installer is a bit dangerous a bit too automated in my opinion, just letting you know you should try to at least have some more user input and a final warning that the installer will overwrite the disk completely for those who may have dual boot setups but maybe you have designed it this way on purpose, do you have much documentation yet? I say this as i didnt try your other two installers that must go on sda2 and sda3, not sure how that works.  

Anyhow just some constructive criticism here, the look and feel of the distro is really nice so well done there.

**Comment by dessington** [comment]
Yes I am yet to make a proper installer for it, but there isn't a single
decent guide out there. It does state on the front page that it
overwrites the existing installation however I'm hoping to integrate
this with the debian installer when someone with the right knowhow can
contribute to the project. 

Thanks for the feedback it helps.

---

Regards,
Jason Dessington
CUSTOMWEB 

On 2020-04-28 12:43, Sigrunnr wrote:

> Hi again, gave your iso a try on a bare metal machine with no operating system so just a test box. The installer is a bit dangerous, just letting you know you should try to at least have some more user input and a final warning that the installer will overwrite the disk completely for those who may have dual boot setups but maybe you have designed it this way on purpose, do you have much documentation yet? I say this as i didnt try your other two installers that must go on sda2 and sda3, not sure how that works. 
> 
> Anyhow just some constructive criticism here, the look and feel of the distro is really nice so well done their. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/dessington/dxt2/issues/2
[2]

**Comment by Sigrunnr** [comment]
My bad i just discovered it on your github frontpage of the project. Might be a good idea to put that info on the website too as i couldn't see it there. I wish i could help with the debian installer but i have no knowledge. You could use something called refractainstaller, although it is for the fork of debian called devuan (non systemd fork). It might be a viable alternative, get in contact with the maintainer he is a friendly person always willing to help.

More info here:
https://sourceforge.net/projects/refracta/files/tools/
https://www.ibiblio.org/refracta/

**Comment by dessington** [comment]
Yes to install to sda2 or sda3 without formatting drive use
installdxt2sda2 or installdxt2sda3 - however this is not extensively
tested. It works for me but as mentioned a proper installer is the way
to go :)

---

Regards,
Jason Dessington
CUSTOMWEB 

On 2020-04-28 12:43, Sigrunnr wrote:

> Hi again, gave your iso a try on a bare metal machine with no operating system so just a test box. The installer is a bit dangerous, just letting you know you should try to at least have some more user input and a final warning that the installer will overwrite the disk completely for those who may have dual boot setups but maybe you have designed it this way on purpose, do you have much documentation yet? I say this as i didnt try your other two installers that must go on sda2 and sda3, not sure how that works. 
> 
> Anyhow just some constructive criticism here, the look and feel of the distro is really nice so well done their. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/dessington/dxt2/issues/2
[2]

**Comment by dessington** [comment]
A standard installer will be uploaded by tomorrow. You'll be able to select region, language, partitioning, etc as with a standard debian instraller.
